name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc run -n trainer -p trainer.depth python train.py

          # Report metrics
          echo "## Metrics" >> report.md
          cat metrics.txt >> report.md
          git fetch --prune
          dvc metrics diff master --show-md >> report.md

          cml-send-comment report.md